### ISSUE TITLE
blawar took down his GitHub, invalid smm2crypt link

### ISSUE THREAD

**Issue by jonbarrow** [0Liam/smm2-documentation#3]
blawar seems to have deleted his GitHub account, which means the link to `smm2crypt` in the [encrypted format](https://github.com/0Liam/smm2-documentation/blob/master/Encrypted%20Format.md) documentation is no longer valid. I also couldn't find any other libs that support encrypting the courses, though to be fair I did not look that much

**Comment by MegaMech** [comment]
<script src="https://unpkg.com/smm2data/index.js"></script>
    <script src="https://unpkg.com/smm2crypt/index.js"></script>

Try those?

**Comment by jonbarrow** [comment]
I have my own encryption module for courses, so I'm good. Just wanted to point out that the linked fork is gone and to my knowledge that was the only public tool currently that could re-encrypt the courses. The library you linked does not support encrypting

**Comment by liamadvance** [comment]
Blawar's account was removed by Github, and I don't think there were any forks of his version. If a different tool is created, I'll change the link.

**Comment by jonbarrow** [comment]
I have written my own library for encrypting. Once I release it I will make a PR. I will keep this open in case someone else links one before me

**Comment by jonbarrow** [comment]
Closing as I have published my tool. See [here](https://github.com/RedDuckss/partrick) for more information
